spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhujie616/my-config-repo.git
          username: zhujie616
          password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
